use gtk::{Builder, Label};

pub struct Labels {
    pub uptime: Label,
    pub cpu_freq: Label,
    pub ram: Label,
    pub swap: Label,
    pub cpu_usage: Label,
    pub processes: Label,
    pub host: Label,
    pub disk_root: Label,
    pub disk_mnt_data: Label,
    pub disk_mnt_warehouse: Label,
    pub net_up: Label,
    pub net_down: Label,
    pub gpu_renderer: Label,
    pub gpu_usage: Label,
    pub vram: Label,
    pub vram_busy: Label,
    pub gpu_clock: Label,
    pub temp_junction: Label,
    pub temp_die: Label,
    pub temp_memory: Label,
    pub power_draw: Label,
    pub power_cap: Label,
    pub voltage: Label,
    pub sclk: Label,
    pub mclk: Label,
    pub fclk: Label,
    pub socclk: Label,
    pub fan: Label,
    pub pcie: Label,
    pub state: Label,
    pub pstate: Label,
}

impl Labels {
    /// Create a Labels struct with empty (invisible) placeholder widgets.
    pub fn default_empty() -> Self {
        Self {
            uptime: Label::builder().build(),
            cpu_freq: Label::builder().build(),
            ram: Label::builder().build(),
            swap: Label::builder().build(),
            cpu_usage: Label::builder().build(),
            processes: Label::builder().build(),
            host: Label::builder().build(),
            disk_root: Label::builder().build(),
            disk_mnt_data: Label::builder().build(),
            disk_mnt_warehouse: Label::builder().build(),
            net_up: Label::builder().build(),
            net_down: Label::builder().build(),
            gpu_renderer: Label::builder().build(),
            gpu_usage: Label::builder().build(),
            vram: Label::builder().build(),
            vram_busy: Label::builder().build(),
            gpu_clock: Label::builder().build(),
            temp_junction: Label::builder().build(),
            temp_die: Label::builder().build(),
            temp_memory: Label::builder().build(),
            power_draw: Label::builder().build(),
            power_cap: Label::builder().build(),
            voltage: Label::builder().build(),
            sclk: Label::builder().build(),
            mclk: Label::builder().build(),
            fclk: Label::builder().build(),
            socclk: Label::builder().build(),
            fan: Label::builder().build(),
            pcie: Label::builder().build(),
            state: Label::builder().build(),
            pstate: Label::builder().build(),
        }
    }

    /// Extract all labelled widgets from the GTK Builder.
    pub fn from_builder(builder: &Builder) -> Self {
        // Just extract each one — this is where we pay the cost once at startup.
        Self {
            uptime: builder.object("lbl_uptime").unwrap(),
            cpu_freq: builder.object("lbl_cpu_freq").unwrap(),
            ram: builder.object("lbl_ram").unwrap(),
            swap: builder.object("lbl_swap").unwrap(),
            cpu_usage: builder.object("lbl_cpu_usage").unwrap(),
            processes: builder.object("lbl_processes").unwrap(),
            host: builder.object("lbl_host").unwrap(),
            disk_root: builder.object("lbl_disk_root").unwrap(),
            disk_mnt_data: builder.object("lbl_disk_mnt_data").unwrap(),
            disk_mnt_warehouse: builder.object("lbl_disk_mnt_warehouse").unwrap(),
            net_up: builder.object("lbl_net_up").unwrap(),
            net_down: builder.object("lbl_net_down").unwrap(),
            gpu_renderer: builder.object("lbl_gpu_renderer").unwrap(),
            gpu_usage: builder.object("lbl_gpu_usage").unwrap(),
            vram: builder.object("lbl_vram").unwrap(),
            vram_busy: builder.object("lbl_vram_busy").unwrap(),
            gpu_clock: builder.object("lbl_gpu_clock").unwrap(),
            temp_junction: builder.object("lbl_temp_junction").unwrap(),
            temp_die: builder.object("lbl_temp_die").unwrap(),
            temp_memory: builder.object("lbl_temp_memory").unwrap(),
            power_draw: builder.object("lbl_power_draw").unwrap(),
            power_cap: builder.object("lbl_power_cap").unwrap(),
            voltage: builder.object("lbl_voltage").unwrap(),
            sclk: builder.object("lbl_sclk").unwrap(),
            mclk: builder.object("lbl_mclk").unwrap(),
            fclk: builder.object("lbl_fclk").unwrap(),
            socclk: builder.object("lbl_socclk").unwrap(),
            fan: builder.object("lbl_fan").unwrap(),
            pcie: builder.object("lbl_pcie").unwrap(),
            state: builder.object("lbl_state").unwrap(),
            pstate: builder.object("lbl_pstate").unwrap(),
        }
    }
}
